services:
  # Frontend Vue.js приложение
  - type: web
    name: listing-auditor-frontend
    env: node
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_SITE_URL
        value: https://listing-auditor-frontend.onrender.com
      - key: SUPABASE_PUBLIC_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false

  # n8n Workflow Automation
  - type: web
    name: listing-auditor-n8n
    env: node
    buildCommand: npm install -g n8n
    startCommand: n8n start
    envVars:
      - key: N8N_HOST
        value: listing-auditor-n8n.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_WEBHOOK_URL
        value: https://listing-auditor-n8n.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MANUS_API_KEY
        sync: false
      - key: BROWSERLESS_URL
        sync: false

  # Supabase Database
  - type: pserv
    name: listing-auditor-db
    env: docker
    dockerfilePath: ./supabase/Dockerfile
    dockerContext: ./supabase
    envVars:
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres
      - key: JWT_SECRET
        sync: false
      - key: ANON_KEY
        sync: false
      - key: SERVICE_ROLE_KEY
        sync: false

  # Browserless (для скриншотов)
  - type: web
    name: listing-auditor-browserless
    env: docker
    dockerfilePath: ./browserless/Dockerfile
    dockerContext: ./browserless
    envVars:
      - key: MAX_CONCURRENT_SESSIONS
        value: 10
      - key: CONNECTION_TIMEOUT
        value: 300000
      - key: MAX_QUEUE_LENGTH
        value: 10

databases:
  - name: listing-auditor-postgres
    databaseName: listing_auditor
    user: listing_auditor_user
